name: Lint

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

permissions:
    checks: write
    contents: write

jobs:
    run-php-linters:
        name: Run PHP linters
        runs-on: ubuntu-latest

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v3

            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.3"
                  coverage: none
                  tools: phpcs, phpcbf

            - name: Run linters
              uses: wearerequired/lint-action@v2
              with:
                  php_codesniffer: true
                  # Optional: Ignore warnings
                  php_codesniffer_args: "-n"

    run-js-linters:
        name: Run JS linters
        runs-on: ubuntu-latest

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 12

            - name: Install Node.js dependencies
              run: npm ci

            - name: Run linters
              uses: wearerequired/lint-action@v2
              with:
                  eslint: true
                  prettier: true

    run-css-linters:
        name: Run CSS linters
        runs-on: ubuntu-latest

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 12

            - name: Install Node.js dependencies
              run: npm ci

            - name: Run linters
              uses: wearerequired/lint-action@v2
              with:
                  stylelint: true
                  prettier: true
    
    run-html-linters:
        name: Run HTML linters
        runs-on: ubuntu-latest

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 12

            - name: Install Node.js dependencies
              run: npm ci

            - name: Run linters
              uses: wearerequired/lint-action@v2
              with:
                  prettier: true
